[theme]
primaryColor="#4a90e2"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#000000"
font="sans serif"


[server]
enableCORS=false
enableXsrfProtection=false

[client]
toolbarMode="minimal"
showErrorDetails=true

[global]
developmentMode=false
